### ISSUE TITLE
New WFS and GeoJSON layer option: projection

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/api-documentation#67]
There is a new undocumented layer option for WFS and GeoJSON layers: "projection".

From PR [#743](https://github.com/origo-map/origo/pull/743):
> Fixes [#734](https://github.com/origo-map/origo/issues/734)
> Adds projection option for wfs and geojson.
> Simply set "projection":"EPSG:4326" to request features in another reference system and Origo will handle the transformation. The proj4Defs has to be configured in index.json unless it's EPSG:4326 or 3857.

**Comment by jokd** [comment]
Yupp, that's a hidden treasure.

**Comment by MattiasSp** [comment]
Ok if I add a PR for this?

**Comment by jokd** [comment]
Absolutely!
